name: CI/CD Pipeline for Calculadora

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install
      
      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install
      
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ubuntu
          DEPLOY_PATH: /var/www/html/calculadora
        run: |
          # Configurar SSH con mayor seguridad
          install -m 700 -d ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          
          # Configurar known_hosts
          ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Prueba de conexión con verbose
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USERNAME@$HOST "echo 'Test connection'"
          
          # Si la conexión es exitosa, proceder con el despliegue
          if [ $? -eq 0 ]; then
            rsync -avz -e "ssh -i ~/.ssh/id_rsa" --delete --exclude 'tests' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH/
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && composer install --no-dev && sudo systemctl restart apache2"
          else
            echo "Error en la conexión SSH"
            exit 1
          fi