name: CI/CD Pipeline for Calculadora

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install
      
      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install
      
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ubuntu
          DEPLOY_PATH: /var/www/html/calculadora
        run: |
          # Crear directorio SSH y configurar permisos
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Iniciar agente SSH
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          
          # Agregar host a known_hosts
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          # Prueba de conexión
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$HOST "echo 'Test connection'"